version: '3'
services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgresql
      - POSTGRES_PASSWORD=production
    ports:
      - 5432
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/blogTestRails
    ports:
      - "3000:3000"
    depends_on:
      - db